name: Deploy Frontend (Vercel)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: |
          # prefer npx to avoid global install issues on Actions runners
          npm ci --silent || true

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if [ -z "$VERCEL_TOKEN" ]; then
            echo "Missing VERCEL_TOKEN secret. Please add it to repository secrets." >&2
            exit 1
          fi
          cd client
          # use npx so we don't rely on global install
          npx vercel --token "$VERCEL_TOKEN" --prod --confirm
