name: Deploy Backend (Fly.io)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install flyctl
        run: |
          # install flyctl using the official installer to a writable location
          curl -L https://fly.io/install.sh | FLYCTL_INSTALL=/tmp sh
          /tmp/bin/flyctl version

      - name: Authenticate flyctl
        env:
          FLYCTL_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          # use the non-interactive login with access token
          /tmp/bin/flyctl auth login --access-token "$FLYCTL_TOKEN"

      - name: Build & Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          # Run flyctl from repository root so the Dockerfile's COPY ./server/ . works
          # and point flyctl to the server's fly.toml and Dockerfile explicitly.
          /tmp/bin/flyctl deploy --config server/fly.toml --dockerfile server/Dockerfile
