name: Deploy Backend (Fly.io)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions@v1
        with:
          version: '0.0.355'

      - name: Authenticate flyctl
        env:
          FLYCTL_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          echo "$FLYCTL_TOKEN" | flyctl auth token

      - name: Build & Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          cd server
          # build not required if using dockerfile inside server
          flyctl deploy --config fly.toml --remote-only
